name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform -chdir=./infra/s3-bucket init

      - name: Terraform Validate
        run: terraform -chdir=./infra/s3-bucket validate

      - name: Terraform Plan
        run: terraform -chdir=./infra/s3-bucket plan

      - name: Terraform Apply
        run: terraform -chdir=./infra/s3-bucket apply -auto-approve
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}